// try - catch
const numero1 = 20;
const numero2 = 30;

try{
    console.log(numero3);
} catch(error){
    console.log(error);
}

console.log(1)